/*
 * @Author: W·S
 * @Date: 2022-09-08 14:13:17
 * @LastEditors: W·S
 * @LastEditTime: 2022-09-25 00:05:47
 * @Description: Description
 */
import type { AppProps } from "next/app";
import type { NextPage } from "next/types";
import type { ReactElement, ReactNode } from "react";
import Head from "next/head";
import { appWithTranslation } from "next-i18next";
import ErrorBoundary from "../components/ErrorBoundary";
import "../styles/globals.scss";
import "../styles/antd.less";

type NextPageWithLayout<P = object, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

const MyApp = ({ Component, pageProps }: AppPropsWithLayout) => {
  const getLayout = Component?.getLayout || ((page: JSX.Element) => page);
  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Next App</title>
      </Head>
      <ErrorBoundary>{getLayout(<Component {...pageProps} />)}</ErrorBoundary>
    </div>
  );
};

export default appWithTranslation(MyApp);
